### PR TITLE
feat(#35):make layout responsive. some layout fixes.

### LINKED ISSUE #35: Update Layout to Be Responsive
The current layout has its main content shifted to the right and is not following the "boxed design" principle. That shall be changed.

# ToDos

- [x] Make the main content follow the "boxed design" principle by adding Tailwind's class `container` to it
- [x] Make the main layout have spacing in a way that leads to the main content being centered on the page
- [x] Make sure paddings / margins are set in a way that makes sense in the layout
- [x] Test different viewports on different pages and potentially update them in the Tailwind config

### PR DESCRIPTION
**Pull request by Marvin-Dem**

### CODE REVIEW

File: src/components/Layout.tsx [hunk 1]
```diff
@@ -28,17 +28,19 @@ export default function Layout({ children }: LayoutProps) {
...
-                                href="https://portfolio-site-marvin.vercel.app/"
-                                target="_blank"
-                            >
-                                About me
-                            </Link>
-                        </footer>
+                <div className="min-h-[calc(100vh-100px)] flex flex-row-reverse justify-between">
+                    <div className="w-full">
+                        <div className="flex items-center flex-col justify-between min-h-full container mx-auto px-[200px]">
+                            <main className="main">{children}</main>
```
Comment (p-runge) [inline src/components/Layout.tsx]: Please remove all remaining custom css classes within the Layout.tsx and replace them by Tailwind ones.

File: src/components/Layout.tsx [hunk 2]
```diff
@@ -28,17 +28,19 @@ export default function Layout({ children }: LayoutProps) {
...
-                            <Link
-                                href="https://portfolio-site-marvin.vercel.app/"
-                                target="_blank"
-                            >
-                                About me
-                            </Link>
-                        </footer>
+                <div className="min-h-[calc(100vh-100px)] flex flex-row-reverse justify-between">
+                    <div className="w-full">
+                        <div className="flex items-center flex-col justify-between min-h-full container mx-auto px-[200px]">
```
Comment (p-runge) [inline src/components/Layout.tsx]: Since the 200px width is caused by the sidebar and occurs on multiple places, it would be a possibility to register it as a custom width in Tailwind.

**Review by p-runge — CHANGES_REQUESTED** [review]

File: tailwind.config.js [hunk 3]
```diff
@@ -2,6 +2,26 @@
...
+                    "100%": { marginLeft: "0", marginRight: "-200px" },
+                },
+                pokeballopening: {
+                    "0%": { "background-position": "-73px 0" },
+                    "99.999%": { "background-position": "-73px 0" },
+                    "100%": { "background-position": "-148px 0" },
+                },
+            },
+            width: {
+                sidebarspace: "200px",
```
Comment (p-runge) [inline tailwind.config.js]: `sidebar` is probably enough. This will result in `w-sidebar` which is fine.

File: src/components/Layout.tsx [hunk 4]
```diff
@@ -10,28 +10,28 @@ export default function Layout({ children }: LayoutProps) {
     return (
         <div className="bg-[url('/fire-bg.jpg')]">
             <div className="bg-[url('/fire-sil.png')] bg-right-bottom bg-no-repeat bg-fixed bg-[length:310px_233px] flex flex-col">
-                <header className="header">
+                <header className="flex justify-between h-[100px] shadow-[0_5px_black]">
```
Comment (p-runge) [inline src/components/Layout.tsx]: The 100px height is a thing that does not only appear here but also in the calculation of the layout's main content. Therefore it would be cleaner to also include it as a custom width in the Tailwind config.

File: src/components/Layout.tsx [hunk 5]
```diff
@@ -10,28 +10,28 @@ export default function Layout({ children }: LayoutProps) {
...
                     <div
                         onMouseEnter={() => {
                             setIsOpen(true);
                         }}
                         onMouseLeave={() => {
                             setIsOpen(false);
                         }}
-                        className="pokeball"
+                        className="flex items-start h-full bg-[url('/pixelpokeball.png')] bg-[0_0] [aspect-ratio:75/100] hover:animate-pokeballopening"
```
Comment (p-runge) [inline src/components/Layout.tsx:21]: Just a hint: `bg-[0_0]` is usually the same as `bg-left-top`. But in this case it's ok to use 0_0 because you are manipulating the position on a pixel base in the animation.

Nothing to be done here. Only a heads-up.

File: tailwind.config.js [hunk 6]
```diff
@@ -2,6 +2,26 @@
...
+                sidebaropening: "sidebaropening 1.5s forwards -0.1s",
+                pokeballopening: "pokeballopening 0.6s forwards 0.2s",
+            },
+            keyframes: {
+                sidebaropening: {
+                    "0%": { marginLeft: "-200px", marginRight: "0" },
+                    "100%": { marginLeft: "0", marginRight: "-200px" },
+                },
+                pokeballopening: {
+                    "0%": { "background-position": "-73px 0" },
```
Comment (p-runge) [inline tailwind.config.js]: Since you are only changing one value (the x value) you can directly set `background-position-x` instead.

File: src/components/Layout.tsx [hunk 7]
```diff
@@ -50,7 +50,7 @@ export default function Layout({ children }: LayoutProps) {
                             onMouseLeave={() => {
                                 setIsOpen(false);
                             }}
-                            className="sidebar"
+                            className="flex flex-col p-1 border-r-4 border-black w-sidebarspace -mr-sidebarspace animate-sidebaropening z-10"
```
Comment (p-runge) [inline src/components/Layout.tsx]: `border-black` is obsolete.

**Review by p-runge — CHANGES_REQUESTED** [review]

**Review by p-runge — APPROVED** [review]
